### ISSUE TITLE
Create awesome ai tools website

### ISSUE THREAD

**Issue by npv2k1** [aliammari/Awesome-Ai-Tools#4]

**Comment by Kamalkoranga** [comment]
what should be its tech stack?

**Comment by npv2k1** [comment]
We can use docusaurus. I built a [template](https://github.com/pnstack/template-docusaurus)

**Comment by aliammari** [comment]
i have added a website, you can find it in the about section

**Comment by aliammari** [comment]
I'd like if you help me with styling using bootstap5, you can find the files in the website branch

**Comment by Kamalkoranga** [comment]
Okay, I will check it ...

**Comment by aliammari** [comment]
awesome.aacoder.me

**Comment by aliammari** [comment]
see the website branch in this repo for the code
